# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Varun Garg
tagline: Dreamer. Sports Fanatic. Toastmaster. Coder" #"<a target='_blank' href='https://en.wikipedia.org/wiki/Yudhishthira'> </a> 
picture: varun.jpg #keep a 100x100 image inside images folder.
email: varungarg2796@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yudish is a minimal Jekyll theme for content oriented websites with less distractions.
baseurl: "/NewBeg" # the subpath of your site, e.g. /blog
#url: "http://webjeda.com" # the base hostname & protocol for your site
brand-color: '#e74c3c'
permalink: ':title/'

# Footer
credits: Varun Garg #credits on the footer
version: 1.0

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

sass:
  style: compressed
  
disqus-shortname: webjeda-sample
analytics: UA-83979019-1

include: [_pages]



#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
  
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes


gems: [jekyll-paginate, jekyll-seo-tag]
